# Generated by Django 5.2.7 on 2025-10-13 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiEcommerceComputerApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='lastname',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='email',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='avatar',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='producto',
        ),
    ]
