# Generated by Django 5.2.7 on 2025-10-13 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiEcommerceComputerApp', '0002_rename_lastname_usuario_apellido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='categoria',
        ),
    ]
