# Generated by Django 5.2.7 on 2025-10-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiEcommerceComputerApp', '0003_alter_categoria_options_alter_categoria_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='roles',
            field=models.CharField(choices=[('admin', 'Administrador'), ('cliente', 'Cliente')], default='CLIENTE', max_length=10),
        ),
    ]
