# Generated by Django 5.2.7 on 2025-10-14 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiEcommerceComputerApp', '0004_alter_usuario_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_creados', to='apiEcommerceComputerApp.usuario'),
        ),
    ]
